/// The product's name: on the start page (when there is no logo), in the PDF's header,
/// in report file names and in the share sheet. Change it here.
const String kBrandName = 'Epile-X';

/// The company line that goes with the name ("Epile-X by NeuraVance Labs"). Empty
/// leaves it out.
const String kBrandByline = 'by NeuraVance Labs';

/// The logo shown on the start page. Replace the file (keep the name), or point
/// this at another asset. Empty shows [kBrandName] as text instead.
const String kLogoAsset = 'assets/brand/logo.png';

/// One line under the name on the start page. Empty hides it.
const String kTagline = '';

/// Where a recording lives: bundled with the app, or a folder on disk.
class DatasetLocation {
  final String path;
  final bool isAsset;

  const DatasetLocation.asset(this.path) : isAsset = true;
  const DatasetLocation.directory(this.path) : isAsset = false;
}

/// The recording the Review page loads. To use another recording, point this at
/// a folder with the same three files (manifest.json, overview.json,
/// windows.bin), for example:
///   const DatasetLocation.directory('/sdcard/Download/my_recording')
/// The bundled default is generated by tools/make_demo_dataset.py.
const DatasetLocation kDatasetLocation = DatasetLocation.asset('assets/demo_recording');

/// The experimental activity-risk readout on the Data page. Set to false to
/// remove it completely: the card, the monitor behind it, and the "Experimental"
/// label all go. It is a demonstration of the idea, not a validated detector.
const bool kShowExperimentalRisk = true;

/// The line shown under the activity-risk number. Empty hides just this line and
/// keeps the readout; [kShowExperimentalRisk] removes the whole thing.
const String kRiskExperimentalNote = 'Experimental, not a diagnosis';

/// Who the start page greets. Fixed for the demo; there are no accounts yet.
const String kUserName = 'Estelle';

/// The picture of the device on the start page. Drop a PNG (a transparent
/// background looks best) at this path and it replaces the placeholder; the file
/// need not exist. Empty always shows the placeholder. To show a real 3D model
/// instead, see `lib/ui/widgets/device_hero.dart`.
const String kDeviceImageAsset = 'assets/brand/device.png';
