/// Name shown on the start page and in reports. Change it here.
const String kBrandName = 'Neuravance';

/// Where a recording lives: bundled with the app, or a folder on disk.
class DatasetLocation {
  final String path;
  final bool isAsset;

  const DatasetLocation.asset(this.path) : isAsset = true;
  const DatasetLocation.directory(this.path) : isAsset = false;
}

/// The recording the Review page loads. To use another recording, point this at
/// a folder with the same three files (manifest.json, overview.json,
/// windows.bin), for example:
///   const DatasetLocation.directory('/sdcard/Download/my_recording')
/// The bundled default is generated by tools/make_demo_dataset.py.
const DatasetLocation kDatasetLocation = DatasetLocation.asset('assets/demo_recording');
